### ISSUE TITLE
Issue authing

### ISSUE THREAD

**Issue by LogicalSoIutions** [SaxyPandaBear/TwitchSongRequests#125]
I authed on twitch no problem
Clicked to auth on spotify - https://i.imgur.com/Q9i3zF2.png

**Comment by SaxyPandaBear** [comment]
Yeah I just figured it out and was going to make an issue to track it. Fixing it atm

**Comment by SaxyPandaBear** [comment]
Basically the issue is I lose the request context when authorizing. I stuck Spotify auth behind Twitch explicitly because the Twitch ID is the identifier. But without passing along the context of who is authorizing, it craps out.

**Comment by SaxyPandaBear** [comment]
@LogicalSoIutions this should be fixed now. I just don't get how cookies work 😓 especially when I need to do a 3rd party authorization in order to get the info I need - I have to auth before I can set the cookie so I don't think strict cookies work. The alternative I guess would be for me to create an ID for a user that is separate. I didn't think it would be worthwhile or beneficial at the time, but maybe it's something I'll have to revisit. 

I tested out logging in, unsubscribing to log out and logging back in and it worked so closing this out. Feel free to reopen if it still is an issue

**Comment by LogicalSoIutions** [comment]
https://i.imgur.com/2XN9K3C.png

**Comment by SaxyPandaBear** [comment]
302 is a redirect. I see a success log in my application for your subscription.

**Comment by LogicalSoIutions** [comment]
Okay, awesome. My buttons didn't change, I had no way to tell it was successful.

**Comment by SaxyPandaBear** [comment]
Yeah #120 is something I need to do to help with that. Sorry that it's not great right now.
