### ISSUE TITLE
[Bug]: Service doesn't work, subscribe button not working either

### ISSUE THREAD

**Issue by itslegiTim** [SaxyPandaBear/TwitchSongRequests#129]
### What happened?

It doesn't work for me. Also I can't click the subscribe button. I don't know, if it collates to the problem of the service not working, but just wanted to mention it.

Twitch Channel is "legiTim"

**Comment by SaxyPandaBear** [comment]
If you can't click on it, that means you're all set up. Have you tried redeeming channel points?

**Comment by itslegiTim** [comment]
Yes, I redeemed them with my own account and the one of my girlfriend, but nothing gets added to the queue unfortunatly.
    Am Samstag, 4. März 2023 um 21:45:12 MEZ hat Andrew Huynh ***@***.***> Folgendes geschrieben:  
 
 


If you can't click on it, that means you're all set up. Have you tried redeeming channel points?

**Comment by SaxyPandaBear** [comment]
Okay, so something is messed up with the subscribe button. Working on it.

**Comment by SaxyPandaBear** [comment]
Basically after you subscribe, it should have something like this, at the moment. I tried to make it so that the button is disabled after you already subscribe, but I tested the flow as myself again and realized it's just always disabled for some reason. I'm not sure why. The subscription should work now. Closing

<img width="334" alt="Screen Shot 2023-03-04 at 10 37 08 PM" src="https://user-images.githubusercontent.com/17056456/222940337-eca15140-7794-4918-b588-6dee9fca3faa.png">
