### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by Matty220** [SaxyPandaBear/TwitchSongRequests#180]
### Your Twitch username

w_matty

**Comment by SaxyPandaBear** [comment]
I see that you went through the onboarding steps, and then deleted yourself
```
{"level":"info","ts":"2023-06-11T22:16:04.898Z","caller":"api/user.go:105","msg":"successfully deleted user 431396665"}
```
One issue with this is that I can't create a new custom reward on your channel again with the same name. Please delete the custom reward I created for your channel, and go through the steps again because I see that I do not have access to events from your channel (the subscribe part)

**Comment by Matty220** [comment]
Sorry for late reply, should be fixed again?

**Comment by SaxyPandaBear** [comment]
Did you hit subscribe? I don't see it updated in my database. I see that you did authorize Twitch/Spotify again yesterday, but it still says that I haven't been granted access to read events from your channel

**Comment by Matty220** [comment]
I did click subscribe again, yes.

**Comment by Matty220** [comment]
Okay, odd, I checked again and logged back in with Twitch and made me click the Subscribe button again. should be fully fixed now? I hope?

**Comment by SaxyPandaBear** [comment]
Alright it looks like that part worked. The issue now is I don't have an email address. I have to manually add an email address for a spotify account to authorize them to use my service. You can drop that here or DM me on discord: saxypandabear 

As of right now, this is the last open spot that I have cause I have onboarded 24/25 allowed users.

**Comment by SaxyPandaBear** [comment]
Added you, thanks for reaching out!

**Comment by Matty220** [comment]
Thanks!
