### ISSUE TITLE
[issue] whenever i type either the song URL in it doesnt queue

### ISSUE THREAD

**Issue by JakeyboySCO** [SaxyPandaBear/TwitchSongRequests#277]
### What happened?

whenever i type either the song URL in it doesnt queue, ive tried online on stream, offline, in chat, in obs and nothing is queuing, maybe im doing something wrong but i feel as though ive read it 3 times or so, thank you for any help.

**Comment by SaxyPandaBear** [comment]
1. This project uses channel points.
2. You aren't onboarded. Spotify limits the number of users I can allow to use my project to 25 people and I haven't found time to write up how to self host it. 

I try to audit who is actually using the service so that I can make room for new people to onboard, and I need to do that again soon so I will go back through the queue of onboarding requests then. Thanks for your patience.

**Comment by JakeyboySCO** [comment]
ok so is it best to get someone else to test it then? sorry for the hassle, my bad, thank you for your help.

**Comment by SaxyPandaBear** [comment]
No, basically what I'm saying is it won't work until I onboard you

**Comment by SaxyPandaBear** [comment]
I'm just going to close this out since you aren't onboarded, so it isn't going to work until then.
